name: Release

on:
  push:
    branches:
      - master

jobs:
  build_Docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: deno-oak
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      - name: Docker use gcloud CLI as credential helper
        run: |
          gcloud auth configure-docker eu.gcr.io -q
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Image
        run: |-
          docker build \
                -t eu.gcr.io/$GCLOUD_PROJECT/$SERVICE_NAME:$GITHUB_SHA \
                --push .
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    needs: build_Docker_image
    defaults:
      run:
        working-directory: gcp
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform set deploy version variable
        run: |
          curl \
            --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request PATCH \
            --data '{
                      "data": {
                        "id":"${{ secrets.TF_APP_VERSION_VAR_ID }}",
                        "type":"vars",
                        "attributes": {
                          "key":"app_version",
                          "value":"${{ github.sha }}"
                        }
                      }
                    }' \
            https://app.terraform.io/api/v2/vars/${{ secrets.TF_APP_VERSION_VAR_ID }}
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
      - name: Terraform Apply
        run: terraform apply -auto-approve

